/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CommentatorData {
	commentatorOne: CommentatorInfo;
	commentatorTwo: CommentatorInfo;
	autoShow: boolean;
	delay: number;
	autoHide: boolean;
	lifetime: number;
}
export interface CommentatorInfo {
	name?: string;
	pronouns?: string;
	tag?: string;
}
