/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreditsData {
	/**
	 * The list of Setup and Teardown volunteers helping with the event.
	 */
	setupTeam: string[];
	/**
	 * The list of Commentators helping with the event.
	 */
	commentaryTeam: string[];
	/**
	 * The list of Stream Technicians helping with the event.
	 */
	techTeam: string[];
	/**
	 * The list of SquidWest TOs and Staff.
	 */
	staffTeam: string[];
	/**
	 * The Head TO for this event.
	 */
	headTO: string[];
	/**
	 * The list of Staff and Pool Captains for this event.
	 */
	poolCaptains: string[];
	/**
	 * The list of Artists contributing to the layouts or event.
	 */
	artTeam: string[];
}
