/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EventData {
	/**
	 * The current event name.
	 */
	eventName: string;
	/**
	 * The Location the event is taking place.
	 */
	eventLocation: string;
	/**
	 * The current event number.
	 */
	eventNumber: number;
}
