/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IntermissionData {
	/**
	 * Whether to display the current time on the Omnibar
	 */
	showTime: boolean;
	/**
	 * Whether to show the current event on the Omnibar
	 */
	showEvent: boolean;
	/**
	 * Whether to show the event location on the Omnibar
	 */
	showLocation: boolean;
	/**
	 * Whether to show custom flavor text on the Omnibar
	 */
	showFlavorText: boolean;
	/**
	 * Flavor Text to display on the Omnibar
	 */
	flavorText: string;
}
